[model]
type = "DenseFLOSigmoid"
hidden_features = [256]
output_features = 128
activation = "elu"
seed = 42

[training]
epochs = 100
batch_size = 128
shuffle = true
save_checkpoint = true
checkpoint_path = "checkpoints/"
log_interval = 10

[optimizer]
type = "adam"
[optimizer.adam]
learning_rate = 0.001

[dataset]
flatten = true
transform = "minmax"
[dataset.minmax]
# need to be broadcastable with the data
in_min = 0
in_max = 255
out_min = -1
out_max = 1

[logging]
log_dir = "logs"
log_level = "info"
use_tensorboard = true