[model]
type = "AntiHebbianTDModule"
seed = 42
[model.kwargs]
n_features = 128
p_target = 0.07
gamma = 0.9
momentum = 0.96
n_input_features = 784 # Poisson spikes FashionMNIST
init_variance_w_forward = 1.0
init_variance_w_prediction = 1.0
[model.seq]
skip_first = 4
   
[dataset.kwargs]
num_steps = 100
max_rate = 0.5

[training]
epochs = 100
batch_size = 64
learning_rate = 0.003

[training.checkpoint]
save = true
save_interval = 5 # epochs
max_to_keep = 12

[training.dataloader]
shuffle = true
# drop the last batch to avoid recompiling jitted functions because of changing input dims
# see here https://flax-linen.readthedocs.io/en/latest/guides/data_preprocessing/full_eval.html
drop_last = true

[validation]
split = 0.16
eval_interval = 12
[validation.dataloader]
batch_size = 256
[validation.sim_fn]
type = "log_and"
quantile = 0.9
[validation.sim_fn.kwargs]
eps = 1.0e-2


