[model]
type = "ConvShift"
seed = 45
[model.kwargs]
features = [256, 256]
conv_sizes = [3, 3]
conv_strides = [1, 2]
padding = "SAME"
   
[dataset]
[dataset.transform.specaugment.kwargs]
n_time_masks = 2
max_time_width = 5
n_freq_masks = 2
max_freq_width = 5

[training]
epochs = 150
batch_size = 64
layer_idx = 0

[training.checkpoint]
save = true
save_interval = 2 # epochs
max_to_keep = 12

[training.dataloader]
shuffle = true
# drop the last batch to avoid recompiling jitted functions because of changing input dims
# see here https://flax-linen.readthedocs.io/en/latest/guides/data_preprocessing/full_eval.html
drop_last = true

[training.loss.sim_fn]
type = "log_and"
[training.loss.sim_fn.kwargs]
eps = 1.0e-2

[training.optimizer]
type = "adamw"
[training.optimizer.kwargs]
learning_rate = 0.001
weight_decay = 0.00001

[validation]
split = 0.16
eval_interval = 12
[validation.dataloader]
batch_size = 128
[validation.sim_fn]
type = "log_and"
quantile = 0.9
[validation.sim_fn.kwargs]
eps = 1.0e-2


